// <auto-generated />
using MessageBoard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MessageBoard.Migrations
{
    [DbContext(typeof(MessageBoardContext))]
    [Migration("20211114230225_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MessageBoard.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Name = "Tech Jobs"
                        },
                        new
                        {
                            GroupId = 2,
                            Name = "Service Jobs"
                        },
                        new
                        {
                            GroupId = 3,
                            Name = "Agriculture Jobs"
                        },
                        new
                        {
                            GroupId = 4,
                            Name = "Food Jobs"
                        },
                        new
                        {
                            GroupId = 5,
                            Name = "Engineering Jobs"
                        },
                        new
                        {
                            GroupId = 6,
                            Name = "Social Services Jobs"
                        },
                        new
                        {
                            GroupId = 7,
                            Name = "Government Jobs"
                        });
                });

            modelBuilder.Entity("MessageBoard.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AuthorName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            AuthorName = "James",
                            Description = "wow a good job",
                            GroupId = 2,
                            Year = 2018
                        },
                        new
                        {
                            MessageId = 2,
                            AuthorName = "Shaun",
                            Description = "wow a bad job",
                            GroupId = 1,
                            Year = 2015
                        },
                        new
                        {
                            MessageId = 3,
                            AuthorName = "Tim",
                            Description = "wow a job",
                            GroupId = 4,
                            Year = 2016
                        },
                        new
                        {
                            MessageId = 4,
                            AuthorName = "Shane",
                            Description = "wow no job",
                            GroupId = 6,
                            Year = 2003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
